#Application Configuration TestIngresoEvertec 
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /tickets-api/v1

spring:
  security:
    user:
      name: admin
      password: Med@ll*103+-*

  # ===============================
  # HEROKU DB
  # ===============================
  datasource:
    username: b5cace9dc15a80
    password: e0799ed6
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com:3306/heroku_cb4d5507151a7e3?reconnect=true

  # ===============================
  # LOCAL DB
  # ===============================
#  datasource:
#    username: root
#    password: Medellin123+-*
#    url: jdbc:mysql://localhost:3306/ticketDb?useUnicode=true&serverTimezone=UTC

  # ===============================
  # JPA / HIBERNATE    MySQL8Dialect
  # ===============================

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    level: org.springframework.web=DEBUG
